spring:
  profiles:
    active: local


logging:
  level:
    root: info
  org:
    hibernate:
      type: trace

---

spring:
  config:
    activate:
      on-profile: staging
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    #spring.datasource.url=jdbc::mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate


springdoc:
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: ${SWAGGER_URL}
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match: /**


logging:
  level:
    root: info
  org:
    hibernate:
      type: trace